builder/build-latest, builder/overlay-rootfs/etc/s6/init-no-catchall/init-stage1
Laurent dixit :-)
```
Since s6-supervise doesn't tell the status file when it has
started, we can't use the same mechanisms to avoid race
conditions as we do to check if the service is up and down -
there's no "status of the supervise process" file.
OK, let's do it another way.
In the overlay, instead of creating the "event" subdirectory for
s6-fdholderd, create the "supervise" subdirectory with rights 0700.
At run time, before forking, run
if { s6-mkfifo -m 0600 /var/run/s6/s6-fdholderd/supervise/control }
and in the background block, run
redirfd -w 3 /var/run/s6/s6-fdholderd/supervise/control
fdclose 3
This will correctly block until s6-supervise has started.
It's a hack because it relies on an internal mechanism of s6-supervise
(we are not supposed to know that s6-supervise opens the …
```
=> avoid no-catchall stage1<->stage2 race condition, thanks Laurent

builder/overlay-rootfs/etc/s6/init/init-stage1, builder/overlay-rootfs/etc/s6/init/init-stage2
* S6_LOGGING behaviour wasn't consistent in two code paths
* by default, keep init.d script env vars clean, don't import cont. envs
=> bug fix & make S6_LOGGING behaviour consistent

builder/build-latest, builder/overlay-rootfs/usr/bin/logutil-newfifo, builder/overlay-rootfs/usr/bin/logutil-service, builder/overlay-rootfs/usr/bin/logutil-service-main
also prefix fifoname in fdholder with the path provided by the user, just to debug issues more easily.
=> add -f opt. in logutil-service to use fifo as input or default to stdin

README.md, builder/build-latest, builder/overlay-rootfs/usr/bin/with-notifywhenup
**WARNING**: `s6-notifywhenup` no longer exists in `s6` package so consequently `with-notifywhenup` was removed from overlay.
=> update to latest skaware: v1.14.0

builder/overlay-rootfs/etc/s6/init/init-stage2
if container was executed using a CMD command, `s6-svscanctl -t` is executed twice. avoid it.
=> avoid calling s6-svscanctl twice #76

README.md, builder/overlay-rootfs/etc/s6/init/init-stage1, builder/overlay-rootfs/usr/bin/printcontenv, builder/overlay-rootfs/usr/bin/with-contenv
When S6_KEEP_ENV var is set, docker environment is not reset
and whole supervision tree has direct access to it.
One might want to use it if secrets are inejcted by `ENTRYPOINT`
prior to executioning overlays `/init` and company policy
prohibits saving secrets to FS.
=> Add new S6_KEEP_ENV mode

README.md, builder/overlay-rootfs/etc/s6/init/init-stage1
When migrating an existing image to a s6-overlay, one might
want to prepend CMD with a previously used `ENTRYPOINT`, so that
new image can be as a drop in replacement and no changes
to the way it is used/called are required.
This is not ideal in the current form as it would split value into separate args (because of `import -s`), but I couldn't figure out how to make `backtick` NOT to set env var if `prog` exited with an error.
=> New S6_CMD_ARG0 variable to prepend CMD when passed to /init

builder/build-latest
Additionally, removing the dbg build - it looks like the only difference
between the builds was the existance of strace, and the download is
returning a 404 error.
=> Adding armhf builds

builder/overlay-rootfs/usr/bin/with-contenv
it was introduced when a fix for import->importas was provided
=> fix: revert back and don't use /bin in with-contenv

builder/overlay-rootfs/etc/s6/init/init-stage2, builder/overlay-rootfs/etc/s6/init/init-stage3
If init or other part of stage 2 fails - container will exit, but the exitcode will be 0
This pull request will make sure container exits with 1 if stage 2 fails
=> Make stage2 exit code available in stage3

builder/overlay-rootfs/etc/s6/init/init-stage2
We are migrating our docker images to use s6-overlay and we want to use S6_CMD_ARG0 as recommended to ease the migration of the entrypoint.  I think that the logging for CMD should honor S6_LOGGING and thus not log "cmd exited 0" to stdout, but rather to s6-uncaught-logs, if S6_LOGGING is enabled.  This can end up polluting stdout of the docker run command and adversely impact piping/parsing etc.  The absence should not be a problem since the return code is available as the return code of the docker run command.
I have attempted to make the s6-echo of the exit more in line with the logging of the other phases by adding "[cmd}" and calling init-stage2-redirfd.  I am new to s6-overlay and execlineb, so my implementation may have some effect I am not aware of, but I hope the intent is …
=> "cmd exited ..." should use init-stage2-redirfd to honor S6_LOGGING.

builder/overlay-rootfs/etc/s6/init/init-stage2
Waiting sequentially is only marginally slower than waiting in parallel,
but in return proper exit code can be set and handled, so that failing
services do fail startup procedure
=> Make S6_CMD_WAIT_FOR_SERVICES to respect S6_BEHAVIOUR_IF_STAGE2_FAILS

README.md, builder/overlay-rootfs/etc/s6/init/init-stage2
Allows the user to specify `S6_READ_ONLY_ROOT=1` when running a container to indicate that user-provided files in `/etc` should be copied to `/var/run/s6` instead of linked. This allows a container using s6-overlay to be run with a read-only root filesystem using
```
docker run --read-only --tmpfs /tmp --tmpfs /run --tmpfs /var:rw,exec ...
```
Based on comments in the init-stage2 source, when using this capability, user-provided files should not use symlinks due to limitations of `s6-hiercopy`.
=> added S6_READ_ONLY_ROOT; copy instead of link user files

builder/overlay-rootfs/etc/s6/services/docker-cmd/finish
The exit code of the command should be stored in `S6_STAGE2_EXITED` instead of `S6_CMD_EXITED`.
`S6_CMD_EXITED` has been renamed by commit e33f6ef3813490198844421c363f780375cad7ab.
=> Fix for issue #216: Store the docker cmd exit code in the proper variable.

builder/overlay-rootfs/etc/s6/init/init-stage1
When `S6_KEEP_ENV` is set to `0`, it is expected to have the container environment reset.  This means that if during the container execution environment variables are created in 
`/var/run/s6/container_environment`, a restart of the container should clear them, which is not the case without this fix.
=> Before creating container environment, make sure to remove any existing one.

builder/overlay-rootfs/etc/s6/init/init-stage2
=> Update init-stage2 to fix "s6-test: fatal: parse error at argument 0"

README.md
When I build this tiny Dockerfile as a test, according to [this tutorial](https://github.com/just-containers/s6-overlay#bin-and-sbin-are-symlinks)
```dockerfile
FROM centos:latest
ADD https://github.com/just-containers/s6-overlay/releases/download/v1.21.4.0/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C / --exclude="./bin" --exclude="./sbin"
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /usr ./bin ./sbin
ENTRYPOINT /init
```
I faced following error
```sh
Step 4/5 : RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /usr ./bin ./sbin
---> Running in 31ca57642a57
tar: ./sbin: Not found in archive
tar: Exiting with failure status due to previous errors
The command '/bin/sh -c tar xzf /tmp/s6-overlay-amd64.tar.gz -C /usr ./bin ./sbin' returned a non-zero code: 2
```
- the …
=> Skip not-existing "./sbin" in tutorial

builder/overlay-rootfs/etc/s6/init/init-stage2
Do not spawn s6-svwait processes for services that are marked `down` as `s6-svscan` will not start them.
=> Ignore down service when waiting for them in init stage 2

README.md, builder/overlay-rootfs/etc/s6/init/init-stage3
If I understand correctly when we run `docker stop $container_id`, docker send a SIGTERM to `s6-svscan`.
Then the program forward `SIGTERM` to s6-supervise which in turn forward the signal to `run` programs.
In parallel, s6-overlay run stage3 that iterate over cont-finish.d scripts and then kills everything by sending again a `SIGTERM`.
In some cases, when we need to do a graceful shutdown we have to trap the signal and perform various operations that can take times.
And in various cases, s6-overlay send the second `SIGTERM` too early and kills those operations.
It should be interesting to wait services before sending `s6-nuke`. 
[https://github.com/amannocci/s6-overlay-fix](https://github.com/amannocci/s6-overlay-fix)
Signed-off-by: amannocci <adrien.mannocci@gmail.com>
=> Wait for services before nuke

builder/overlay-rootfs/etc/s6/init/init-stage2-fixattrs.txt
A ./data/check script is executed by "s6-notifyoncheck" to implement notification readiness in daemons that don't natively support it:
https://skarnet.org/software/s6/s6-notifyoncheck.html
=> Ensure any ./data/check script is executable

README.md
I think the order is reversed in the two examples
=> Fixed order of permission

builder/overlay-rootfs/etc/s6/init/init-stage1, builder/overlay-rootfs/etc/s6/init/init-stage2
I'm the Alpine package maintainer for s6-overlay. Alpine's Edge
"bleeding edge" version has execline 2.8.0.0 packaged and as a result
my s6-overlay 2.2.0.3 package is giving errors due to a change in
"backtick" behaviour as of execline 2.8.0.0 (detailed here:
http://skarnet.org/software/execline/upgrade.html).
This PR fixes the init-stage1 and init-stage2 scripts to work with the
newer version of execline.
=> Fix backtick commands for execline 2.8.0.0

.github/workflows/release.yml, README.md
A few notes:
* I updated the Quick Start to use the `ARG` directive to set a variable with the current version, and updated the rest of the documentation to use that variable. This way in future documentation updates, we only need to update that ARG variable in the Quick Start.
* Ran into a small issue - running `make ARCH=arm-linux-musleabi` and `make ARCH=arm-linux-musleabihf` both produce tarballs named `s6-overlay-arm-${VERSION}.tar.xz`. So in the CI, [I rename `s6-overlay-arm-${VERSION}.tar.xz` to `s6-overlay-armhf-${VERSION}.tar.xz`](https://github.com/jprjr/s6-overlay/blob/70146fd62744fe679992e70b62dda88305b6856b/.github/workflows/release.yml#L40-L55). Not sure if the build system should be updated to handle that, or if it should stay in the CI layer.
* As discussioned in #352 - no …
=> Create automatic release process, update documentation

README.md
It wouldn't run unless I got rid of the spaces, as [shellcheck suggested](https://github.com/koalaman/shellcheck/wiki/SC2283). As it is currently was giving me 
`./finish: 6: ./finish: e: not found`
=> Fix syntax for finish script example in README

.github/workflows/release.yml
this one uses nodejs16 which is not deprecated  
closes #509
=> ci: upgrade actions/checkout to v3

README.md
Fixes typo with package to install for alpine machines to extract s6-overlay during installation in alpine machines. The `xz-utils` [doesn't exist](https://pkgs.alpinelinux.org/packages?name=xz-utils&branch=edge&repo=&arch=&maintainer=), but rather it's equivalent `xz` [does](https://pkgs.alpinelinux.org/packages?name=xz&branch=edge&repo=&arch=&maintainer=).
=> specify correct package to install for extraction on alpine machines
